var goodsAllList = [
       {
       	 "goodsPic":"img/index/goodsPic/goods01.jpg",
       	 "info":"小狗（puppy）小型手持立",
       	 "price":"￥359"      	 
       },
       {
       	 "goodsPic":"img/index/goodsPic/goods02.jpg",
       	 "info":"洗衣液",
       	 "price":"￥35"       	 
       },
       {
       	 "goodsPic":"img/index/goodsPic/goods03.jpg",
       	 "info":"洗手液",
       	 "price":"￥39"
       },
       {
       	 "goodsPic":"img/index/goodsPic/goods04.jpg",
       	 "info":"宝宝乐",
       	 "price":"￥59"
       },
       {
       	 "goodsPic":"img/index/goodsPic/goods01.jpg",
       	 "info":"小狗（puppy）小型手持立",
       	 "price":"￥359"
       },
       {
       	 "goodsPic":"img/index/goodsPic/goods03.jpg",
       	 "info":"小狗（puppy）小型手持立",
       	 "price":"￥359"
       },
       {
       	 "goodsPic":"img/index/goodsPic/goods04.jpg",
       	 "info":"小狗（puppy）小型手持立",
       	 "price":"￥359"
       },
       {
       	 "goodsPic":"img/index/goodsPic/goods01.jpg",
       	 "info":"小狗（puppy）小型手持立",
       	 "price":"￥359"
       }
]
